version: "2"

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - bodyclose

linters-settings:
  revive:
    rules:
      - name: exported
        arguments: [disableStuttering]